### ISSUE TITLE
Do not use quotes around real-valued parameter ranges in param.ccl

### ISSUE THREAD

**Issue by ianhinder** [ianhinder/Kranc#109]
Kranc currently adds quotes around parameter ranges in param.ccl files for parameters which are not strings.  It shouldn't.

See also https://trac.einsteintoolkit.org/ticket/1595.

**Comment by rhaas80** [comment]
This was fixed in 1e30463 "Correct formatting of parameter value ranges" Wed Jun 3 16:02:07 2015 -0400 I believe. The piraha parser would fail to accept such a quoted range as far as I know as well.

**Comment by stevenrbrandt** [comment]
Piraha will accept it, but will generate a warning.
