### ISSUE TITLE
kranccode.org not reachable

### ISSUE THREAD

**Issue by rhaas80** [ianhinder/Kranc#145]
http://kranccode.org/ which is the page linked to on the ET download page: http://einsteintoolkit.org/download.html is no longer reachable. One gets an error message:
> You have reached a domain that is pending ICANN verification.

The full error webpage is:
<blockquote>
As of January 1, 2014 the Internet Corporation for Assigned Names and Numbers (ICANN) will mandate that all ICANN accredited registrars begin verifying the Registrant WHOIS contact information for all new domain registrations and Registrant contact modifications.
Why this domain has been suspended

Email address has not been verified.
This is a new domain registration and the Registrant email address has not been verified.

or

The Registrant contact data for this domain was modified but still requires verification.
Specifically the First Name, Last Name and/or email address have been changed and never verified.
<blockquote>

**Comment by ianhinder** [comment]
Sigh.  Namecheap emailed and said there was this change coming up, but that I didn't need to do anything.  I'll ask them.  They're usually very good.  My other domains are working fine, but that one is listed as "suspended".

**Comment by rhaas80** [comment]
This seems to work again.

**Comment by ianhinder** [comment]
Yes; sorry I forgot to update.  Namecheap responded to my email saying it was a fault with the upstream provider.  The workaround was to disable whoisguard, and apparently this is OK because the whois entry doesn't contain personal information anyway.  In which case, I'm not sure what whoisguard is for, but hey...
